repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--verbose', '--']
      - id: cargo-check
        args: ['--workspace', '--all-targets', '--all-features']
      - id: clippy
        args: ['--workspace', '--all-targets', '--all-features', '--', '-D', 'warnings']

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.25
    hooks:
      - id: typos
